//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exam22stol.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class customers
    {
        public int ID_Customers { get; set; }
        public string Name { get; set; }
        public string F_Name { get; set; }
        public string S_Name { get; set; }
        public Nullable<int> ID_Role { get; set; }
        public Nullable<int> ID_Applications { get; set; }
        public Nullable<int> ID_Catolog { get; set; }
        public string Login { get; set; }
        public string Passvord { get; set; }
    
        public virtual Applications Applications { get; set; }
        public virtual Role Role { get; set; }
        public virtual Сatalog Сatalog { get; set; }
    }
}
