//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exam22stol.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class web22Entities : DbContext
    {
        public web22Entities()
            : base("name=web22Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<Basket> Basket { get; set; }
        public virtual DbSet<Consumables> Consumables { get; set; }
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<Listofclients> Listofclients { get; set; }
        public virtual DbSet<Malfunctions> Malfunctions { get; set; }
        public virtual DbSet<ReconciliationReport> ReconciliationReport { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<specialty> specialty { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Telephone> Telephone { get; set; }
        public virtual DbSet<Typesoftelephone> Typesoftelephone { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
        public virtual DbSet<worker> worker { get; set; }
        public virtual DbSet<Сatalog> Сatalog { get; set; }
    }
}
