//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exam22stol.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReconciliationReport
    {
        public int ID_Reconciliationreport { get; set; }
        public string Theactofthesender { get; set; }
        public string Theactwasreceived { get; set; }
        public string Data { get; set; }
        public string Time { get; set; }
        public Nullable<int> ID_Malfunctions { get; set; }
        public Nullable<int> ID_Listofclients { get; set; }
    
        public virtual Listofclients Listofclients { get; set; }
        public virtual Malfunctions Malfunctions { get; set; }
    }
}
