//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exam22stol.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int ID_Warehouse { get; set; }
        public string ProductName { get; set; }
        public string NameoftheConsumable { get; set; }
        public string quantity { get; set; }
        public string Shelf { get; set; }
        public string Shelving { get; set; }
        public Nullable<int> ID_Consumablestypes { get; set; }
        public Nullable<int> ID_Wolker { get; set; }
    
        public virtual Consumables Consumables { get; set; }
        public virtual worker worker { get; set; }
    }
}
